### ISSUE TITLE
self in callback

### ISSUE THREAD

**Issue by algermissen** [Galeria-Kaufhof/ha-jobs#1]
Sending a closure over self to a child to be notified upon 'touch-failure' is nice

```
val lockKeeper = context.actorOf(
        KeepJobLockedActor.props(lockRepo, job.jobType, jobId, job.lockTimeout, () => self ! LostLock(jobContext)),
        job.jobType.name + "_LOCK")
```

(ha-jobs-core/src/main/scala/de/kaufhof/hajobs/JobExecutor.scala)

I would not have thought that it is ok to do that, but now it seems pretty clear. Thanks!

**Comment by magro** [comment]
Great! Can we can close this question then?
