### ISSUE TITLE
actor lock existing more than once

### ISSUE THREAD

**Issue by alex4567** [Galeria-Kaufhof/ha-jobs#12]
Multiple service Instances logged
actor name [<Jobname>_LOCK] is not unique!
One of the Instances at least got in trouble because of C*-Timeouts.
After restarting that instance the errors from the other instances disappeared, too.
`
akka.actor.InvalidActorNameException: actor name [AttributeModifications_LOCK] is not unique! at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:130) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at akka.actor.dungeon.Children$class.reserveChild(Children.scala:76) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at akka.actor.ActorCell.reserveChild(ActorCell.scala:369) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at akka.actor.dungeon.Children$class.makeChild(Children.scala:201) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at akka.actor.dungeon.Children$class.actorOf(Children.scala:37) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at akka.actor.ActorCell.actorOf(ActorCell.scala:369) ~[com.typesafe.akka.akka-actor_2.11-2.3.11.jar:na] at de.kaufhof.hajobs.JobExecutor$$anonfun$de$kaufhof$hajobs$JobExecutor$$run$1.apply(JobExecutor.scala:88) ~[de.kaufhof.ha-jobs_2.11-1.0.2.jar:1.0.2] at de.kaufhof.hajobs.JobExecutor$$anonfun$de$kaufhof$hajobs$JobExecutor$$run$1.apply(JobExecutor.scala:80) ~[de.kaufhof.ha-jobs_2.11-1.0.2.jar:1.0.2]
`

**Comment by magro** [comment]
I just released ha-jobs 1.1.1 to have more information when this happens again, please update to this version.
