### ISSUE TITLE
Is the lock touched immediately after obtaining it?

### ISSUE THREAD

**Issue by algermissen** [Galeria-Kaufhof/ha-jobs#3]
It appears to me that the lock touching actor KeepJobLockedActor is touching the lock immediately after creation leading to a lock touch immediately after lock acquiring.

See https://github.com/Galeria-Kaufhof/ha-jobs/blob/master/ha-jobs-core/src/main/scala/de/kaufhof/hajobs/KeepJobLockedActor.scala#L23
and https://github.com/Galeria-Kaufhof/ha-jobs/blob/master/ha-jobs-core/src/main/scala/de/kaufhof/hajobs/JobExecutor.scala#L88

Is that intentional or am I not getting something?

**Comment by magro** [comment]
You're right. Initially we were using the KeepJobLockedActor differently, now it makes sense to change it. I'll submit a pull request with this...

**Comment by magro** [comment]
@algermissen Are you going to do the review + merge?

**Comment by MarcoPriebe** [comment]
already merged
